using System.Text.Json.Serialization;
using WishfulClaw.Contracts;
using WishfulClaw.Core.Tools;
using WishfulClaw.Infrastructure.Db;
using WishfulClaw.Workspace.Memory;
using WishfulClaw.Agent;
using WishfulClaw.Agent.Modules.Git;
using WishfulClaw.Agent.Modules.Extensions;
using WishfulClaw.Worker.Modules;

namespace WishfulClaw.Worker;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
    GenerationMode = JsonSourceGenerationMode.Metadata)]
[JsonSerializable(typeof(ErrorResult))]
[JsonSerializable(typeof(StatusResult))]
[JsonSerializable(typeof(WorkerRoutesResult))]
[JsonSerializable(typeof(SimpleOkResult))]
[JsonSerializable(typeof(SimpleSuccessResult))]
[JsonSerializable(typeof(ProviderTestResult))]
[JsonSerializable(typeof(GoalSimpleResult))]
[JsonSerializable(typeof(GoalActionResult))]
[JsonSerializable(typeof(GoalRunStateChanged))]
[JsonSerializable(typeof(GoalStatusResponse))]
[JsonSerializable(typeof(GoalLiveResponse))]
[JsonSerializable(typeof(DbInitializeResult))]
[JsonSerializable(typeof(ProjectFindResult))]
[JsonSerializable(typeof(ProjectDeleteResult))]
[JsonSerializable(typeof(ProjectRow))]
[JsonSerializable(typeof(List<ProjectRow>))]
[JsonSerializable(typeof(SessionFindResult))]
[JsonSerializable(typeof(SessionMutationResult))]
[JsonSerializable(typeof(SessionClearAllResult))]
[JsonSerializable(typeof(SessionResetResult))]
[JsonSerializable(typeof(SessionStatusResult))]
[JsonSerializable(typeof(SessionRow))]
[JsonSerializable(typeof(List<SessionRow>))]
[JsonSerializable(typeof(MessageMutationResult))]
[JsonSerializable(typeof(MessageDeleteResult))]
[JsonSerializable(typeof(MessageCountResult))]
[JsonSerializable(typeof(MessageDeleteLastResult))]
[JsonSerializable(typeof(MessageCompactResult))]
[JsonSerializable(typeof(MessageUsageStatsResult))]
[JsonSerializable(typeof(MessageRow))]
[JsonSerializable(typeof(SshConnectionFindResult))]
[JsonSerializable(typeof(SshMutationResult))]
[JsonSerializable(typeof(SshConnectionDbRow))]
[JsonSerializable(typeof(List<SshConnectionDbRow>))]
[JsonSerializable(typeof(PlanFindResult))]
[JsonSerializable(typeof(PlanMutationResult))]
[JsonSerializable(typeof(PlanRow))]
[JsonSerializable(typeof(List<PlanRow>))]
[JsonSerializable(typeof(GoalFindResult))]
[JsonSerializable(typeof(GoalMutationResult))]
[JsonSerializable(typeof(GoalEventFindResult))]
[JsonSerializable(typeof(GoalEventMutationResult))]
[JsonSerializable(typeof(GoalRow))]
[JsonSerializable(typeof(List<GoalRow>))]
[JsonSerializable(typeof(GoalEventRow))]
[JsonSerializable(typeof(List<GoalEventRow>))]
[JsonSerializable(typeof(GoalPageResult))]
[JsonSerializable(typeof(GoalEventPageResult))]
[JsonSerializable(typeof(GoalReopenResult))]
[JsonSerializable(typeof(SubAgentRunRow))]
[JsonSerializable(typeof(List<SubAgentRunRow>))]
[JsonSerializable(typeof(PluginSessionFindResult))]
[JsonSerializable(typeof(PluginSessionMutationResult))]
[JsonSerializable(typeof(PluginRouteSessionResult))]
[JsonSerializable(typeof(PluginSessionRow))]
[JsonSerializable(typeof(PluginProjectRow))]
[JsonSerializable(typeof(PluginSessionMessageRow))]
[JsonSerializable(typeof(SubAgentFindResult))]
[JsonSerializable(typeof(SubAgentIndexResult))]
[JsonSerializable(typeof(SubAgentSessionSummary))]
[JsonSerializable(typeof(SubAgentSimpleResult))]
[JsonSerializable(typeof(MemorySearchResult))]
[JsonSerializable(typeof(MemoryStats))]
[JsonSerializable(typeof(MemoryFrontmatter))]
[JsonSerializable(typeof(MemoryReadResult))]
[JsonSerializable(typeof(MemorySearchResponse))]
[JsonSerializable(typeof(MemoryMutationResult))]
[JsonSerializable(typeof(MemoryDemotionCandidate))]
[JsonSerializable(typeof(List<MemoryDemotionCandidate>))]
[JsonSerializable(typeof(MemoryDemotionCandidatesResponse))]
[JsonSerializable(typeof(MemoryBatchStatusResult))]
[JsonSerializable(typeof(MemoryEntryRow))]
[JsonSerializable(typeof(List<MemoryEntryRow>))]
[JsonSerializable(typeof(MemoryEntriesByStatusResponse))]
[JsonSerializable(typeof(AgentRuntimeRunResult))]
[JsonSerializable(typeof(AgentRuntimeCancelResult))]
[JsonSerializable(typeof(AgentRuntimeStopResult))]
[JsonSerializable(typeof(AgentRuntimeAppendMessagesResult))]
[JsonSerializable(typeof(AgentRuntimeReverseResponseResult))]
[JsonSerializable(typeof(PlanState))]
[JsonSerializable(typeof(PlanStep))]
[JsonSerializable(typeof(GoalState))]
[JsonSerializable(typeof(GoalPlanItem))]
[JsonSerializable(typeof(AgentRuntimeStreamEvent))]
[JsonSerializable(typeof(AgentRuntimeStreamEnvelope))]
[JsonSerializable(typeof(AgentRuntimeToolUseBlock))]
[JsonSerializable(typeof(AgentRuntimeToolResult))]
[JsonSerializable(typeof(AgentRuntimeToolCallState))]
[JsonSerializable(typeof(AgentRuntimeRequestDebugInfo))]
[JsonSerializable(typeof(AgentRuntimeTokenUsage))]
[JsonSerializable(typeof(AgentRuntimeRequestTiming))]
[JsonSerializable(typeof(GitExecResult))]
[JsonSerializable(typeof(GitStatusDetailedResult))]
[JsonSerializable(typeof(GitStatusDetailed))]
[JsonSerializable(typeof(GitStatusFile))]
[JsonSerializable(typeof(GitQueryResult))]
[JsonSerializable(typeof(GitCommitHistoryItem))]
[JsonSerializable(typeof(GitBranchItem))]
[JsonSerializable(typeof(GitRepositorySummary))]
[JsonSerializable(typeof(NativeExtensionToolExecutionResult))]
[JsonSerializable(typeof(ToolDefinition))]
[JsonSerializable(typeof(ToolResult))]
[JsonSerializable(typeof(SessionRestoreResponse))]
[JsonSerializable(typeof(ClearSessionResult))]
[JsonSerializable(typeof(List<MessageRow>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<MemorySearchResult>))]
[JsonSerializable(typeof(List<SubAgentSessionSummary>))]
[JsonSerializable(typeof(List<GitStatusFile>))]
[JsonSerializable(typeof(List<GitCommitHistoryItem>))]
[JsonSerializable(typeof(List<GitBranchItem>))]
[JsonSerializable(typeof(List<GoalPlanItem>))]
[JsonSerializable(typeof(List<PlanStep>))]
[JsonSerializable(typeof(List<PluginSessionRow>))]
[JsonSerializable(typeof(List<PluginSessionMessageRow>))]
[JsonSerializable(typeof(ProjectListRow))]
[JsonSerializable(typeof(ProjectListResult))]
[JsonSerializable(typeof(SessionListRow))]
[JsonSerializable(typeof(ProjectDetailResult))]
[JsonSerializable(typeof(CreateSessionResult))]
[JsonSerializable(typeof(GlobalTaskCreateToolResult))]
[JsonSerializable(typeof(GlobalTaskMutationToolResult))]
[JsonSerializable(typeof(GlobalDispatchCreateToolResult))]
[JsonSerializable(typeof(GlobalDispatchUpdateToolResult))]
[JsonSerializable(typeof(List<ProjectListRow>))]
[JsonSerializable(typeof(List<SessionListRow>))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(ProviderTestModelsResult))]
[JsonSerializable(typeof(ProviderModelInfo))]
[JsonSerializable(typeof(SystemMemorySnapshot))]
public sealed partial class WishfulClawJsonContext : JsonSerializerContext
{
}